%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This application generates .mif and .hex files for Altera 
% memories initialization
%
%   Tested on Quartus 15.1
%
%   By Claudio Avi Chami
%   06/Aug/2016
%
% VISIT FPGA SITE: https://fpgasite.wordpress.com
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%-------------------------------------------------------------------
% Generate Parameters
%
ram_size    = 256;     % In words
word_size   = 16;      % Can be 8, 16, 32, etc. 


%-------------------------------------------------------------------
% generate vector with random values witnin a defined range
%
min_v = 100;
max_v = 20000;

% Check values and calculate range
if (min_v < 0)
    min_v = 0;
end
max_val = 2^word_size-1;
if (max_v > max_val)
    max_v = max_val;
end
range_v = max_v - min_v;

values = (randi(range_v - 1, ram_size, 1)) + min_v;


%-------------------------------------------------------------------
% Open mif file for write
%
fileID = fopen('init_mem.mif', 'w');
fprintf( fileID, '%s\n', '-- Generated by mif_gen Matlab script');
fprintf( fileID, '%s\n\n', '-- FPGA SITE - https://fpgasite.wordpress.com');
fprintf( fileID, '%s%d%s\n', 'WIDTH=', word_size, ';');
fprintf( fileID, '%s%d%s\n\n', 'DEPTH=', ram_size, ';');
fprintf( fileID, '%s\n', 'ADDRESS_RADIX=HEX;');
fprintf( fileID, '%s\n\n', 'DATA_RADIX=HEX;');
fprintf( fileID, '%s\n', 'CONTENT BEGIN');

% data format
fdata = int2str(word_size/4);
faddr = int2str(log2(ram_size)/4);
format_str = strcat('    %0', faddr, 'X  :  %0', fdata, 'X;\n');

% write values to file
idx = 0;
for ii=1:ram_size
    fprintf( fileID, format_str, idx, values(idx+1));
    idx = idx+1;
end
fprintf( fileID, '%s\n', 'END;');

fclose( fileID);


%-------------------------------------------------------------------
% Convert to HEX
%

cmd = 'D:\altera_lite\15.1\quartus\bin64\mif2hex keys.mif init_mem.hex';
system(cmd);

    